### ISSUE TITLE
folder not found for folder_id when moving a dashboard

### ISSUE THREAD

**Issue by jaredsohn** [looker-open-source/looker-sdk-ruby#8]
I'm using this command to move a dashboard:

```
sdk.move_dashboard("81", "1735")
```

The error is:

Error summary:
  field: folder_id
  code: missing
  message: folder not found for folder_id
  documentation_url: http://docs.looker.com/ // See: http://docs.looker.com/

If I use the instance API explorer with the same parameters it works fine.

If I do a `copy_dashboard`, it makes a copy of the dashboard but ignores the folder_id.

I'm using version 0.1.2 of the API.

**Comment by ricardomr-google** [comment]
This is a working syntax for the endpoints:

```
sdk.copy_dashboard('1', {}.to_json, {folder_id: '2'})
sdk.move_dashboard('1', {}.to_json, {folder_id: '2'})
```
