### ISSUE TITLE
Bug in streaming client

### ISSUE THREAD

**Issue by alexf101** [looker-open-source/looker-sdk-ruby#88]
Hey, we ran into a bug when using the streaming client where it gets a 401 back from the Looker server and ignores the error.

I suspect the following code in the `build_response` method of the streaming client:
https://github.com/looker-open-source/looker-sdk-ruby/blob/92cb759090d44f9fa8524a552508d8e6cbcdcb6e/lib/looker-sdk/client.rb#L393-L415.

It looks to me like it's avoid calling the block handler if the response code isn't 200, but it's not actually raising an exception. The `unless progress` thing is also always true if the HTTP connection opened, even if the response status is not 200, so we found in practice that our code ignored this error.

I'm guessing this should be refactored to use the error handling code here? https://github.com/looker-open-source/looker-sdk-ruby/blob/92cb759090d44f9fa8524a552508d8e6cbcdcb6e/lib/looker-sdk/error.rb#L33-L58

**Comment by drstrangelooker** [comment]
Can you share more, like a sample call that has this problem?

Thanks

**Comment by alexf101** [comment]
@drstrangelooker Sure!

Any call using streaming has this problem, because it's in the authentication layer.

We happen to use csv form, but I don't think it matters

To replicate the bug, simply use the streaming query mode by passing in a block to `run_inline_query`:
```
query = {
    model: "<redacted>",
    view: "<redacted>",
    fields: ["<redacted>"],
    limit: 100000000,
    filters: {"<redacted>" => "24-11-12 03:00:00 to 2024-12-12 03:00:00"},
    sorts: ["<redacted> asc"]
}
looker_sdk.run_inline_query('csv', query) do |data, progress|
    # .... process the data in chunks
    # BUG: Sometimes, this block will NEVER get called, and a trace reveals that the Looker query received a 401
end
# BUG: However, the code here will execute; that is, no exception gets raised
```

I can see in our trace (pictured below) that the query returns a 401 error every now and then, but no exception gets raised - it just doesn't call the block.

<img width="558" alt="Screenshot 2024-12-06 at 10 51 34 am" src="https://github.com/user-attachments/assets/bd222c3d-d7f3-40a4-8988-e0ecf205b43b">

**Comment by drstrangelooker** [comment]
Just for clarification, is the 401 happening on the first response, or a subsequent part of the stream?

**Comment by drstrangelooker** [comment]
I just opened a branch with a few changes.  Do you want to pull that branch and test it for me? I don't have a sample case that has multiple chunks.

https://github.com/looker-open-source/looker-sdk-ruby/tree/fix-streaming-error-handling
